# Generated by Django 2.1.7 on 2020-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='Anônimo', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default='Descrição')),
                ('tempo', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=50)),
                ('connectivity', models.BooleanField(default=True)),
            ],
        ),
    ]
